name: Test with a workflow

on:
  workflow_dispatch:
    inputs:
      input-b:
        default: foo.bar
        description: input-b
        required: false
      milliseconds:
        description: milliseconds
        default: 20
        required: false
      time-to-live:
        required: false
        description: time-to-live
        default: 100
      enabled:
        description: enabled
        default: true
        required: false

permissions:
  contents: read

jobs:
  test-job:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Input Validation
        uses: ./
        with:
          input-b: ${{ inputs.input-b }}
          milliseconds: ${{ inputs.milliseconds }}
          time-to-live: ${{ inputs.time-to-live }}
          enabled: ${{ inputs.enabled }}

          validation-script: |
            input-b:
              must-be: regex
              value: 'foo\.bar.*' # must be ecma scripts regex
            milliseconds:
              must-be: number
            time-to-live:
              must-be: number
              less-than: 1000
              greater-than: 0
            enabled:
              must-be: boolean
            unknown:
              required: false # should not appear in the report if not valid
              must-be: number
